<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Azure.Storage.Blobs" Version="12.25.0" />
		<PackageReference Include="FirebaseAdmin" Version="3.3.0" />
		<PackageReference Include="Google.Analytics.Data.V1Beta" Version="1.0.0-beta6" />
		<PackageReference Include="AutoMapper" Version="14.0.0" />
		<PackageReference Include="CloudinaryDotNet" Version="1.27.6" />
		<PackageReference Include="Google.Apis.Auth" Version="1.70.0" />
		<PackageReference Include="Google.Apis.Drive.v3" Version="1.69.0.3783" />
		<PackageReference Include="Google.Apis.Oauth2.v2" Version="1.68.0.1869" />
		<PackageReference Include="Google.Cloud.Firestore" Version="3.10.0" />
		<PackageReference Include="MailKit" Version="4.12.1" />
		<PackageReference Include="MegaApiClient" Version="1.10.4" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.15" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.15" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.15">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.15" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.15">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
		<PackageReference Include="MimeKit" Version="4.12.0" />
		<PackageReference Include="payOS" Version="1.0.8" />
		<PackageReference Include="Quartz" Version="3.15.0" />
		<PackageReference Include="Quartz.Extensions.Hosting" Version="3.15.0" />
		<PackageReference Include="StackExchange.Redis" Version="2.8.37" />
	</ItemGroup>
  <ItemGroup>
    <Folder Include="Enum\" />
    <Folder Include="Mapper\" />
    <Folder Include="Entity\" />
    <Folder Include="Payload\Request\" />
    <Folder Include="Utils\" />
  </ItemGroup>

</Project>
